# Generated by Django 3.2.8 on 2021-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
