# Generated by Django 3.2.8 on 2021-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_alter_member_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
