# Generated by Django 3.2.8 on 2021-11-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0005_alter_member_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='img',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
        migrations.AddField(
            model_name='member',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
